env: ${ENV:-production}
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: ${SERVER_COMPRESSION_ENABLED:true}
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: ${SERVER_COMPRESSION_MIN_RESPONSE_SIZE:1024}
  http2:
    enabled: ${SERVER_HTTP2_ENABLED:true}
team: 
  name: "team-name"

spring:
  application:
    name: ${project.artifactId}
    group: ${project.groupId}
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@${SPRING_DATASOURCE_URL:localhost}:${SPRING_DATASOURCE_PORT:1521}:${SPRING_DATASOURCE_DATABASE_NAME:xe}"
    username: ${SPRING_DATASOURCE_USERNAME:teste}
    password: ${SPRING_DATASOURCE_PASSWORD:teste}

notification:
  enabled: ${NOTIFICATION_ENABLED:false}
  sentry:
    enabled: ${NOTIFICATION_SENTRY_ENABLED:false}
    dsn: ${NOTIFICATION_SENTRY_DSN:url}

security:
  jwt:
    enabled: ${SECURITY_JWT_ENABLED:false}
    token:
      secret-key: ${SECURITY_JWT_TOKEN_SECRETKEY}

build:
  version: ${project.version}